Gaussian Filter or Blus: Used to reduce image noise and reduce detail.

* 1D Gaussian: `G(x, n) = (exp(-x² / 2 * n²)) / (2 * pi *  n²) ** 0.5`
* 2D Gaussian: `G(x, y, n) = (exp(-(x² + y²) / 2 * n²)) / (2 * pi *  n²)`

where n is standard deviation

In [ ]:
import numpy as np

In [ ]:
# Implementation of 2d Discrete Gaussian Filter

def gauss_blur_2d(x, y, n=1.0):
  return np.exp(-(x ** 2 + y ** 2) / (2 * (n ** 2))) / (2 * np.pi * (n ** 2))

In [ ]:
filter_size = (5, 5)

# initialize gauss filter 
g = np.zeros(filter_size)

for i in range(filter_size[0]):
  x = i - np.floor(filter_size[0] / 2).astype(int)
  for j in range(filter_size[1]):
    y = j - np.floor(filter_size[1] / 2).astype(int)
    g[i, j] = int(gauss_blur_2d(x, y))
  
print(g)

[[8. 1. 1. 1. 8.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [8. 1. 1. 1. 8.]]
