Gaussian Filter or Blus: Used to reduce image noise and reduce detail.

* 1D Gaussian: `G(x, n) = (exp(-x² / 2 * n²)) / (2 * pi *  n²) ** 0.5`
* 2D Gaussian: `G(x, y, n) = (exp(-(x² + y²) / 2 * n²)) / (2 * pi *  n²)`

where n is standard deviation

In [40]:
import numpy as np
from matplotlib import pyplot as plt

In [44]:
# Implementation of 2d Discrete Gaussian Filter

def gauss_blur_2d(x, y, n=1.0):
  return np.exp(-((x ** 2) + (y ** 2)) / (2 * (n ** 2))) / (2 * np.pi * (n ** 2))

In [48]:
filter_size = (5, 5)

x = np.floor(filter_size[0] / 2).astype(int)
y = np.floor(filter_size[1] / 2).astype(int)
_x = np.arange(-x, x + 1, 1)
_y = np.arange(-y, y + 1, 1)

xx, yy = np.meshgrid(_x, _y)

print(gauss_blur_2d(xx, yy) * 273)

[[ 0.79580168  3.56653569  5.88022325  3.56653569  0.79580168]
 [ 3.56653569 15.98410401 26.35333227 15.98410401  3.56653569]
 [ 5.88022325 26.35333227 43.44929946 26.35333227  5.88022325]
 [ 3.56653569 15.98410401 26.35333227 15.98410401  3.56653569]
 [ 0.79580168  3.56653569  5.88022325  3.56653569  0.79580168]]
