**Harris Corner Direction**:

Unlike edges, corners pixels have high difference in all direction

WSSD(weighted sum of square difference) but with small patch
* E = sum_for_all_pixels_i(w(i) * [I(xi + u, yi + v) - I(xi, yi)



In [ ]:
import numpy as np

In [ ]:
# Implementation of 2d Discrete Gaussian Filter

def gauss_blur_2d(x, y, n=1.0):
  return np.exp(-(x ** 2 + y ** 2) / (2 * (n ** 2))) / (2 * np.pi * (n ** 2))

In [ ]:
filter_size = (5, 5)

# initialize gauss filter 
g = np.zeros(filter_size)

for i in range(filter_size[0]):
  x = i - np.floor(filter_size[0] / 2).astype(int)
  for j in range(filter_size[1]):
    y = j - np.floor(filter_size[1] / 2).astype(int)
    g[i, j] = int(gauss_blur_2d(x, y))
  
print(g)

[[8. 1. 1. 1. 8.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [8. 1. 1. 1. 8.]]
